In [1]:
from pykrx import stock
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/Administrator/Desktop/전종목정보.csv')

#불러오면 종목코드가 int로 바뀌는 현상이 나타나서 다시 Zerofill 진행
df['Code'] = df['Code'].apply(lambda x : str(x).zfill(6))

In [3]:
#연도별로 데이터 가져오기
stock_2022 = stock.get_market_fundamental("20221229", market="ALL")
stock_2021 = stock.get_market_fundamental("20211230", market="ALL")
stock_2020 = stock.get_market_fundamental("20201230", market="ALL")
stock_2019 = stock.get_market_fundamental("20191230", market="ALL")
stock_2018 = stock.get_market_fundamental("20181228", market="ALL")
stock_2017 = stock.get_market_fundamental("20171228", market="ALL")

#종목코드 컬럼 생성
stock_2022['Code'] = stock_2022.index
stock_2021['Code'] = stock_2021.index
stock_2020['Code'] = stock_2020.index
stock_2019['Code'] = stock_2019.index
stock_2018['Code'] = stock_2018.index
stock_2017['Code'] = stock_2017.index

#연도 컬럼 생성
stock_2022['연도']= 2022
stock_2021['연도']= 2021
stock_2020['연도']= 2020
stock_2019['연도']= 2019
stock_2018['연도']= 2018
stock_2017['연도']= 2017

#사용되는 종목 필터링
stock_2022 = stock_2022[stock_2022["Code"].isin(df.Code)]
stock_2021 = stock_2021[stock_2021["Code"].isin(df.Code)]
stock_2020 = stock_2020[stock_2020["Code"].isin(df.Code)]
stock_2019 = stock_2019[stock_2019["Code"].isin(df.Code)]
stock_2018 = stock_2018[stock_2018["Code"].isin(df.Code)]
stock_2017 = stock_2017[stock_2017["Code"].isin(df.Code)]

#인덱스 초기화
stock_2022 = stock_2022.reset_index(drop=True)
stock_2021 = stock_2021.reset_index(drop=True)
stock_2020 = stock_2020.reset_index(drop=True)
stock_2019 = stock_2019.reset_index(drop=True)
stock_2018 = stock_2018.reset_index(drop=True)
stock_2017 = stock_2017.reset_index(drop=True)

In [4]:
#데이터 concat 후 저장
stock = pd.concat([stock_2022,stock_2021,stock_2020,stock_2019,stock_2018,stock_2017], ignore_index=True)
stock.to_csv('연도별재무정보추가데이터.csv', index=False, encoding='UTF-8-sig')

In [5]:
stock

         BPS     PER   PBR   EPS   DIV  DPS    Code    연도
0        829   63.48  2.53    33  0.00    0  060310  2022
1       8075    3.35  0.71  1707  4.72  270  095570  2022
2      10088   13.36  1.56  1179  0.63  100  054620  2022
3      12713    4.67  1.44  3932  1.31  240  265520  2022
4       5714  101.52  1.76    99  0.70   70  211270  2022
...      ...     ...   ...   ...   ...  ...     ...   ...
11497   7555   18.29  1.15   475  1.15  100  189980  2017
11498   8475   11.05  0.63   484  0.00    0  000540  2017
11499   1406    0.00  0.53     0  0.67    5  003280  2017
11500   3510   27.81  1.32   167  2.15  100  037440  2017
11501   5381   15.54  4.45  1541  0.00    0  238490  2017

[11502 rows x 8 columns]